version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.arm
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
